/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SerialsIndexImport } from './routes/serials/index'
import { Route as ProfileIndexImport } from './routes/profile/index'
import { Route as MoviesIndexImport } from './routes/movies/index'
import { Route as CartoonsIndexImport } from './routes/cartoons/index'
import { Route as SerialsSerialsIdImport } from './routes/serials/$serialsId'
import { Route as MoviesMoviesIdImport } from './routes/movies/$moviesId'
import { Route as CartoonsCartoonsIdImport } from './routes/cartoons/$cartoonsId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const SerialsIndexRoute = SerialsIndexImport.update({
  path: '/serials/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any)

const MoviesIndexRoute = MoviesIndexImport.update({
  path: '/movies/',
  getParentRoute: () => rootRoute,
} as any)

const CartoonsIndexRoute = CartoonsIndexImport.update({
  path: '/cartoons/',
  getParentRoute: () => rootRoute,
} as any)

const SerialsSerialsIdRoute = SerialsSerialsIdImport.update({
  path: '/serials/$serialsId',
  getParentRoute: () => rootRoute,
} as any)

const MoviesMoviesIdRoute = MoviesMoviesIdImport.update({
  path: '/movies/$moviesId',
  getParentRoute: () => rootRoute,
} as any)

const CartoonsCartoonsIdRoute = CartoonsCartoonsIdImport.update({
  path: '/cartoons/$cartoonsId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cartoons/$cartoonsId': {
      id: '/cartoons/$cartoonsId'
      path: '/cartoons/$cartoonsId'
      fullPath: '/cartoons/$cartoonsId'
      preLoaderRoute: typeof CartoonsCartoonsIdImport
      parentRoute: typeof rootRoute
    }
    '/movies/$moviesId': {
      id: '/movies/$moviesId'
      path: '/movies/$moviesId'
      fullPath: '/movies/$moviesId'
      preLoaderRoute: typeof MoviesMoviesIdImport
      parentRoute: typeof rootRoute
    }
    '/serials/$serialsId': {
      id: '/serials/$serialsId'
      path: '/serials/$serialsId'
      fullPath: '/serials/$serialsId'
      preLoaderRoute: typeof SerialsSerialsIdImport
      parentRoute: typeof rootRoute
    }
    '/cartoons/': {
      id: '/cartoons/'
      path: '/cartoons'
      fullPath: '/cartoons'
      preLoaderRoute: typeof CartoonsIndexImport
      parentRoute: typeof rootRoute
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesIndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/serials/': {
      id: '/serials/'
      path: '/serials'
      fullPath: '/serials'
      preLoaderRoute: typeof SerialsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  CartoonsCartoonsIdRoute,
  MoviesMoviesIdRoute,
  SerialsSerialsIdRoute,
  CartoonsIndexRoute,
  MoviesIndexRoute,
  ProfileIndexRoute,
  SerialsIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cartoons/$cartoonsId",
        "/movies/$moviesId",
        "/serials/$serialsId",
        "/cartoons/",
        "/movies/",
        "/profile/",
        "/serials/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/cartoons/$cartoonsId": {
      "filePath": "cartoons/$cartoonsId.tsx"
    },
    "/movies/$moviesId": {
      "filePath": "movies/$moviesId.tsx"
    },
    "/serials/$serialsId": {
      "filePath": "serials/$serialsId.tsx"
    },
    "/cartoons/": {
      "filePath": "cartoons/index.tsx"
    },
    "/movies/": {
      "filePath": "movies/index.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.tsx"
    },
    "/serials/": {
      "filePath": "serials/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
